meta:
  engine: 4.1.0 # Min Ergogen version for KiCad 8 footprints
units:
  kx: cx
  ky: cy
  px: kx + 4
  py: ky + 4
  $default_width: cx-0.5
  $default_height: cy-0.5
points:
  zones:
    matrix:
      # Fix placement on KiCAD sheet.
      anchor:
        shift: [150, -150]
      key:
        # Horizontal spacing.
        spread: kx
        # Vertical spacing.
        padding: ky
      columns:
        pinky:
          key:
            splay: 17
            origin: [0, -ky]
            bind: [0.1, 0.5 kx, 0.1, 0.1]
          rows:
            bottom:
              column_net: P102
            home:
              column_net: P2
            top:
              column_net: P0
        ring:
          key:
            stagger: ky
            splay: -7
            origin: [0, -ky]
            bind: [0.1, 0.5 kx, 0.1, 0.1]
          rows:
            bottom:
              column_net: P101
            home:
              column_net: P3
            top:
              column_net: P1
        middle:
          key:
            stagger: ky/3
            splay: -5
            origin: [0, -ky]
            bind: [0.1, 0.1, 0.5 kx, 0.1]
            shift: [0.2, 0]
          rows:
            bottom:
              column_net: P7
            home:
              column_net: P4
            top:
              column_net: P21
        index:
          key:
            stagger: -ky/3
            splay: -5
            origin: [0, -ky]
            bind: [0.1, 0.1, 0.5 kx, 0.5 kx]
          rows:
            bottom:
              column_net: P8
            home:
              column_net: P5
            top:
              column_net: P20
        inner:
          key:
            spread: kx + 1
            stagger: -ky/6
            origin: [0, -ky]
            bind: [0.1, 0.1, 0.1, 0.5 kx]
          rows:
            bottom:
              column_net: P9
            home:
              column_net: P6
            top:
              column_net: P19
    thumbfan:
      anchor:
        ref: matrix_inner_bottom
        shift: [-1.1 kx, -1.5 ky]
      columns:
        home:
          key:
            spread: kx
            splay: -15
            origin: [0 kx, -4.5 ky]
            column_net: P107
        near:
          key:
            spread: kx
            splay: -15
            origin: [-0.5 kx, -1 ky]
            column_net: P15
        far:
          key:
            spread: kx
            splay: -15
            origin: [-0.5 kx, -1 ky]
            column_net: P14
      rows:
        thumb:
          row_net: GND

outlines:
  raw:
    - what: rectangle
      where: true
      bound: true
      asym: left
      size: [kx,ky]
      corner: 1
  # Key outlines with 0.5mm removed to show key overlaps.
  keys:
    - what: rectangle
      where: true
      size: [kx-0.5,ky-0.5]
  board:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: matrix_inner_top
          shift: [-0.5 kx + 1, 0.5 py + ky / 6]
        - ref: matrix_inner_top
          shift: [0.5 px, 0.5 py + ky / 6]
        - ref: matrix_inner_top
          shift: [1.6 px, 0.5 py + ky / 6]
        - ref: matrix_inner_top
          shift: [1.6 px, -3.5 ky]
        - ref: thumbfan_far_thumb
          shift: [0.5 px, 0.5 py]
        - ref: thumbfan_far_thumb
          shift: [0.5 px, 0.5 py]
        - ref: thumbfan_far_thumb
          shift: [0.5 px, -0.5 py]
        - ref: thumbfan_home_thumb
          shift: [0.5 px, -0.7 py]
        - ref: matrix_pinky_bottom
          shift: [0.5 px, -0.5 py]
        - ref: matrix_pinky_bottom
          shift: [-0.5 px, -0.5 py]
        - ref: matrix_pinky_top
          shift: [-0.5 px, 0.5 py]
        - ref: matrix_pinky_top
          shift: [0.56 px, 0.5 py]
        - ref: matrix_ring_top
          shift: [-0.5 px, 0.5 py]
        - ref: matrix_ring_top
          shift: [ 0.57 px, 0.5 py]
        - ref: matrix_middle_top
          shift: [-0.5 px, 0.5 py]
        - ref: matrix_middle_top
          shift: [ 0.5 px, 0.5 py]
        - ref: matrix_index_top
          shift: [-0.54 px, 0.5 py]
        - ref: matrix_index_top
          shift: [0.5 kx, 0.5 py]
  controller:
    - what: rectangle
      where:
        ref: matrix_inner_top
        shift: [25, -4.5]
      size: [19, 34]
  jst_bat:
    - what: rectangle
      where:
        ref: matrix_inner_bottom
        shift: [14, 7.3]
      size: [7.6, 5.9]
  power_button:
    - what: rectangle
      where:
        ref: matrix_inner_bottom
        shift: [31, 0.85]
      size: [5.8, 5.8]
  reset_button:
    - what: rectangle
      where:
        ref: matrix_inner_bottom
        shift: [31, 7.85]
      size: [7, 4.5]
  rotary_encoder:
    - what: circle
      where:
        ref: matrix_inner_bottom
        shift: [20, -14]
      radius: 10
  tenting_puck:
    - what: circle
      where:
        ref: matrix_index_bottom
        shift: [-5.85, -21.5]
      radius: 20.5
  layout_tester:
    - name: board
    - name: keys
      operation: subtract
    - name: controller
      operation: subtract
    - name: jst_bat
      operation: subtract
    - name: power_button
      operation: subtract
    - name: reset_button
      operation: subtract
    - name: rotary_encoder
      operation: subtract
    - name: tenting_puck
      operation: subtract
pcbs:
  c-dux:
    template: kicad8
    outlines:
      main:
        outline: board
    footprints:
      choc_hotswap:
        what: ceoloide/switch_choc_v1_v2
        where: true
        params:
          side: F
          choc_v1_support: true
          choc_v2_support: false
          reversible: true
          hotswap: true
          include_keycap: true
          locked_traces_vias: true
          hotswap_pads_same_side: true
          include_corner_marks: true
          # Kailh spec found on LCSC uses 1.9mm diameter for outer stabilizers, but its too large.
          # Most opensource footprint uses 1.7mm diameter.
          # I measured my choc v1 switches and its 1.6mm thus I'm using 1.7mm here.
          choc_v1_stabilizers_diameter: 1.7
          # 3D model from https://github.com/infused-kim/kb_ergogen_fp/tree/main/3d_models
          hotswap_3dmodel_filename: ${EG_INFUSED_KIM_3D_MODELS}/Choc_V1_Hotswap.step
          # If side is B, need following offset.
          # hotswap_3dmodel_xyz_offset: [-5, -9.7, 0]
          # include_plated_holes: true # Do not know how to use this.
          from: "{{column_net}}"
          to: GND
      mcu_l:
        what: ceoloide/mcu_supermini_nrf52840
        params:
          reversible: false
          show_silk_labels_on_both_sides: true
          # This makes left hand side RAW on top left.
          # reverse_mount: true
          # reversible: true
          # only_required_jumpers: true
          include_extra_pins: true
          # 3D model from https://github.com/infused-kim/kb_ergogen_fp/tree/main/3d_models
          mcu_3dmodel_filename: ${EG_INFUSED_KIM_3D_MODELS}/Nice_Nano_V2.step
        where:
          ref: matrix_inner_top
          shift: [25, -4.5]
          rotate: 0
      jst_bat:
        what: ceoloide/battery_connector_jst_ph_2
        params:
          reversible: false
          include_silkscreen_on_both_sides: true
          BAT_P: BRAW
          BAT_N: GND
        where:
          ref: matrix_inner_bottom
          shift: [13.5, 6.5]
          rotate: 90
      power_button:
        what: power_switch_tht_top_self_lock
        params:
          side: F
          # switch_3dmodel_filename: ''
          show_silk_labels_on_both_sides: true
          PAD_1: RAW
          PAD_2: BRAW
        where:
          ref: matrix_inner_bottom
          shift: [31.1, -1.3]
          rotate: 90
      reset_button:
        what: reset_switch_smd_top
        params:
          side: F
          reversible: true
          PAD_1: GND
          PAD_3: RST
        where:
          ref: matrix_inner_bottom
          shift: [31.64, -25.12]
          rotate: 270
      rotary_encoder:
        what: ceoloide/rotary_encoder_ec11_ec12
        params:
          reversible: true
          # 3D model from https://github.com/foostan/kbd/blob/main/kicad-packages3D/kbd.3dshapes
          encoder_3dmodel_filename: ${KICAD8_3RD_PARTY}/3dmodels\kbd.3dshapes/RotarryEncoder_EC12-SW.step
          A: P10
          B: GND
          C: P16
          S1: GND
          S2: P18
        where:
          ref: matrix_inner_bottom
          shift: [20, -14]
          rotate: 90
      tening_puck:
        what: tenting_puck
        params:
          side: F
        where:
          ref: matrix_index_bottom
          shift: [-5.87, -22.1]
          rotate: 39
      c_dux_text:
        what: ceoloide/utility_text
        params:
          text: 'c-dux by cyf\ndesigned with\nErgogen'
          reversible: true
        where:
          ref: matrix_pinky_bottom
          shift: [0.95 kx, 0 ky]
      ergogen_logo:
        what: ceoloide/utility_ergogen_logo
        params:
          reversible: true
        where:
          ref: matrix_pinky_bottom
          shift: [0.95 kx, -0.38 ky]
